### ISSUE TITLE
Khazad, Anubis not ciphered in right size blocks

### ISSUE THREAD

**Issue by norkator** [norkator/cryptography#21]
Need to fix in some point. Leads to basically input bytes not being ciphered at all.

**Comment by justinearlesmith** [comment]
> Need to fix in some point. Leads to basically input bytes not being ciphered at all.

Thank I did not realize that was part of the issue.
[IntelGFXCoin.log](https://github.com/norkator/cryptography/files/5235070/IntelGFXCoin.log)

**Comment by SKR301** [comment]
Sent a PR to solve the padding issue.
