### ISSUE TITLE
AES return byte array to base64 change 

### ISSUE THREAD

**Issue by norkator** [norkator/cryptography#30]
![128469408-8c3300a4-51ab-42ff-aa7a-57396575bac8](https://user-images.githubusercontent.com/55850510/128634070-96a93220-4c2f-411c-b5fd-849dff2c53f2.png)

@SKR301 https://github.com/norkator/cryptography/pull/29

**Comment by SKR301** [comment]
![image](https://user-images.githubusercontent.com/47807051/128638944-5353c2e0-8099-4c1d-a9f4-61e19207cc8f.png)

https://security.stackexchange.com/questions/220560/rsa-key-string-vs-hex-vs-base64-vs-byte-array-represantational-form
No need to change. It's the same thing.

**Comment by norkator** [comment]
Wait... I need to maybe change something
