### ISSUE TITLE
VIC cipher

### ISSUE THREAD

**Issue by norkator** [norkator/cryptography#40]
Add VIC cipher: https://en.wikipedia.org/wiki/VIC_cipher

Part of the user comment: "...American scientists in the cold war Era and was pretty historically famous. It is probably the most sophisticated "by hand" cipher that can be done in reasonable time with only pen and paper...."

After developing/adding it here, will add to to Cryptography Android app.

**Comment by norkator** [comment]
![job](https://user-images.githubusercontent.com/55850510/133314021-b0a65a96-dad7-4b10-a641-33b065ed0786.png)

**Comment by norkator** [comment]
![u](https://user-images.githubusercontent.com/55850510/133908584-891db1aa-c348-4578-81a7-9b4227aae5a0.gif)

**Comment by SKR301** [comment]
Imagine if I put this on resume and the recruiter actually see these gifs😂😂
Direct entry to senior level

**Comment by norkator** [comment]
> Imagine if I put this on resume and the recruiter actually see these gifs😂😂
> Direct entry to senior level

@SKR301 I know what you mean
![tub](https://user-images.githubusercontent.com/55850510/133919410-3e26eade-a7c0-472f-bde0-37b044dd5496.png)

**Comment by SKR301** [comment]
TACO TACO BURRITTO!!

![](https://cdn.quotesgram.com/img/45/64/1653698884-tumblr_lnxix0PZbR1qli6g7o1_1280.png)

**Comment by norkator** [comment]
> TACO TACO BURRITTO!!
> 
> ![](https://camo.githubusercontent.com/02221e78acd94709c884d0c1af90c270a54ff8a3e28d1121622653f1a0561194/68747470733a2f2f63646e2e71756f7465736772616d2e636f6d2f696d672f34352f36342f313635333639383838342d74756d626c725f6c6e78697830505a625231716c693667376f315f313238302e706e67)

![Screenshot_20210920-111241_Chrome](https://user-images.githubusercontent.com/55850510/133973166-2b946be7-3b4d-4f1f-9c25-b3f69127b842.jpg)

**Comment by SKR301** [comment]
When can I get my payment boss!

https://blog.hawkhost.com/wp-content/uploads/2013/10/cartman-money.gi

**Comment by norkator** [comment]
> When can I get my payment boss!

Oh Jeez, you know that will be hard you know we need to deal with all those papers jeez no yeah, yeah jeez no. Yeah. No.
![20210920-212050](https://user-images.githubusercontent.com/55850510/134054077-f8860687-3493-4e9a-bc49-887c09d1c607.jpg)
