### ISSUE TITLE
bnb136ns6lfw4zs5hg4n84vdloke7hq4m4gtkgf23

### ISSUE THREAD

**Issue by Sanky411** [norkator/cryptography#69]

**Comment by Sanky411** [comment]
![Screenshot_20230130-185439_Trust Wallet.jpg](https://user-images.githubusercontent.com/121991533/215555647-7e11d570-76b3-46de-84e7-7280c56208cf.jpg)

**Comment by norkator** [comment]
Spam / scammer. Closing.
